### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by dragosvr92** [LMOspaceace/ajaxchat#28]
Hello, First i must mention that i am very grateful for the dedication you two put into porting this extension to 3.1. But i have to question some things that could use an improvement.. 
1. It is a huge inconvenient that you must always delete the chat data when updating.
   It makes the Archive feature useless. The tables are there and unchanged. I dont understand why the data must always be deleted. I dont understand why it simply cant use the old 3.0 data. 
2. The extension inserts extra columns into the users table that cannot be removed when uninstalling the extension. Deleting the extension data should delete every database changes made by the extension.... Thats an extension rule as far as im aware. It shouldnt leave leftovers after removal. 

The extra settings shouldnt be added on a extra column in the users table, but create an independent table where these settings are attached to the user id. Like the phpbb_topics_posted table for example. 
1. I dont like that it abusively inserts an additional bbcode for the default chat colour. It should simply use the default text/link colours of the style itself. This causes a huge issue on different dark/white based styles as it has already been discussed. 

Thats all i had to say. Keep up the good work :)

**Comment by LMOspaceace** [comment]
1) some of the code changes that get made require the data to be deleted and some do not. this still being in beta, should not be used on a live forum in the first place so any inconvenience, however unfortunate, is to be expected at this stage.

2) those columns not getting removed has been addressed and will be fixed in the next release.

as for the added bbcode. that is for the font colour hold function. if you don't like having it added, then don't use the extension.

**Comment by dragosvr92** [comment]
But the db-data remains the same. There are no table alterations in the new ver and i am only curious to understand why it cant hold and reuse previous data. If it is a must to delete saved code data, then maybe @Reaper88 can find a way to provide multiple data deletions. By default, only delete php and html data, and for complete extension removal from the db, to use a different uninstall script to remove everything. 

Moving the extension settings to only one table without affecting phpbb tables sounds like a cleaner way to manage the data and export it. 

I am not here to complain but to point out what could use an improvement, from my point of view. There is no need to take it like personal criticism.

**Comment by LMOspaceace** [comment]
your comment... "I dont like that it abusively inserts an additional bbcode for the default chat colour"

that bbcode is not being added abusively, it is there to serve a purpose for the font colour hold.

as for the db, yes, the actualy data is the same, but the extension system has many issues. one issue is when an extension gets updated, depending on what changes get made, in order to add additional elements the extension system will not let you just disable and enable to apply the changes. you have to delete the data and enable to get the extension to load all the db changes. i'm not writing a new migration file for every update as some people have done as it makes for unnecessarily added files to bloat the package. if having the previous chat messages in place is really that important, then back up the chat table and restore it. even i delete the data when i upgrade.

**Comment by dragosvr92** [comment]
I am saying that because it doesnt say anywhere its being added and what it is for. People will wonder where it appeared from... What extension and what it is used for. 

Im not saying to write a migration. I was suggesting the idea to simply not remove any of the data inside the database when removing the extension data. Before uninstalling, they will be just informed that the uninstall wont remove the database entries, and to do that, they will have to run a separate script. Thoughts?

**Comment by LMOspaceace** [comment]
the extension system does not work like modifications do. you are not supposed to use separate uninstall scripts to remove the extension data. the migration files add and remove the data. most of the changes lately have been for the ACP module which has to add things to the db. in order for those changes to be made to the db, the data has to be deleted for the migration files to add the new data. this also resolves issues where some db info gets removed and/or new things get added. in the next version, all db changes will get reverted when the data gets deleted.
